name: Deploy MCPConnect

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Source shell configuration to load PATH
            source ~/.bashrc 2>/dev/null || true
            source ~/.profile 2>/dev/null || true

            # Add npm global bin to PATH
            export PATH=$PATH:$(npm config get prefix 2>/dev/null)/bin

            cd /root/mcpconnect
            git pull origin main
            pnpm install --frozen-lockfile
            pnpm build
            pm2 reload mcpconnect
            echo "Deployment completed at $(date)"
