name: Publish to NPM

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace

      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build
        run: pnpm build

      - name: Prepare for publishing
        run: node scripts/version-bump.js ${{ steps.get_version.outputs.VERSION }} --prepare-publish

      - name: Publish packages
        run: pnpm publish:packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Restore workspace dependencies
        run: pnpm restore-workspace-deps

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}

            ## Changes
            See the [changelog](https://github.com/rocket-connect/mcpconnect/blob/main/CHANGELOG.md) for details.

            ## Installation
            ```bash
            npx @mcpconnect/cli@${{ steps.get_version.outputs.VERSION }}
            ```
          draft: false
          prerelease: false
